# general
#batch_size: 128
batch_size: 4
input_size: 112
embd_shape: 512
sub_name: 'arc_res50'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead # 'ArcHead', 'NormHead'
is_ccrop: False # central-cropping or not

# train
train_dataset: './data/0606_17_16.tfrecord'
binary_img: True
num_classes: 85742
num_samples: 5822653
#num_classes: 13
#num_samples: 79
epochs: 100
base_lr: 0.01
w_decay: !!float 5e-4
save_steps: 1000
#save_steps: 10

# test
test_dataset: '/your/path/to/test_dataset'
